#!/bin/sh

set -e

cd "$(git rev-parse --show-toplevel)"

LC_ALL=C.UTF-8 shellcheck "$@" \
    CI-Examples/bash/scripts/bash_test.sh \
    CI-Examples/common_tools/benchmark-http.sh \
    CI-Examples/python/run-tests.sh \
    tools/gramine.in \
    scripts/clean-check \
    scripts/clean-check-prepare \
    scripts/clean-check-test-copy \
    scripts/download \
    scripts/gitignore-test \
    scripts/run-pylint \
    .ci/run-shellcheck
