name: 🧭 Feature request
description: Suggest a feature
body:
  - type: textarea
    attributes:
      label: Description of the feature
      description: |
        Please be precise and concise.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why Gramine should implement it?
      description: |
        Features introduce complexity and add maintenance cost. Please ensure that this cost is justified.
    validations:
      required: true

