blank_issues_enabled: true
contact_links:
  - name: 💬 I need help with Gramine usage
    url: https://github.com/gramineproject/gramine/discussions/categories/general
    about: Open a discussion thread
