ARG GRAMINE_IMAGE=gramineproject/gramine:stable-focal

FROM ${GRAMINE_IMAGE}

# ARGs cannot be grouped since each FROM in a Dockerfile initiates a new build
# stage, resulting in the loss of ARG values from earlier stages.
ARG GRAMINE_URL=https://github.com/gramineproject/gramine.git

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
       build-essential \
       autoconf \
       bison \
       gawk \
       git \
       meson \
       nasm \
       libunwind-dev \
       ninja-build \
       pkg-config \
       python3 \
       python3-click \
       python3-jinja2 \
       python3-pip \
       python3-pyelftools \
       python3-pytest \
       wget && \
    python3 -m pip install \
       'meson>=0.56' \
       'tomli>=1.1.0' \
       'tomli-w>=0.4.0' && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

RUN git clone --depth 1 --branch v$(gramine-direct --version | cut -d' ' -f2) \
    ${GRAMINE_URL} gramine && \
    cd gramine && \
    meson setup \
        build/ \
        --prefix=/usr \
        -Ddirect=disabled \
        -Dsgx=disabled \
        -Dtests=enabled \
        -Dforce_sgx_tests=enabled && \
    meson compile -C build/ && \
    meson install -C build/

RUN gramine-sgx-gen-private-key

ENTRYPOINT ["/usr/bin/gramine-test"]
