# TODO: This file is only here for the `clean` and `distclean` target, which clean up after Python
# tests (`regression.py`). It can be removed when the tests are moved to Meson.

.PHONY: all
all: ;

.PHONY: clean
clean:
	$(RM) -r __pycache__

.PHONY: distclean
distclean: clean
